apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: default
  labels:
    app: menu
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: menu
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
